# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: uslugibg_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uslugibg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Additional settings for debugging
    command: 
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_connections=on"
    # Ensure the container restarts if it fails
    restart: unless-stopped

volumes:
  postgres_data:
    name: uslugibg_postgres_data